import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner"
import "./globals.css";
import "./fonts.css"
import "./effects.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className=" poppins-light no-scrollbar selection:bg-transparent"
      >
        {children}
        <Toaster/>
      </body>
    </html>
  );
}
