import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className=" poppins-regular"
      >
        {children}
        <Toaster/>
      </body>
    </html>
  );
}
